site_name: "CiviCRM per a entitats del sector social dels Jesu茂tes de Catalunya"
site_description: 'Aquesta documentaci贸 recull les funcionalitats pr貌pies de CiviCRM com tamb茅 les implementades a mida i necessries per reflectir els processos relacionats amb la gesti贸 de les diferents entitats del sector social dels Jesu茂tes de Catalunya.'
site_author: 'Francesc Bassas i Bullich'
site_url: http://docs.crm.socialsj.cat
repo_url: https://github.com/babu-cat/civicrm-for-socialsj-doc

nav:
- Introducci贸: 'index.md'
- CiviCRM:
    - 'Qu猫 茅s CiviCRM': 'civicrm/index.md'
    - 'Contactes': 'civicrm/contactes.md'
    - 'Activitats': 'civicrm/activitats.md'
    - 'Relacions': 'civicrm/relacions.md'
    - 'Grups': 'civicrm/grups.md'
    - 'Permisos': 'civicrm/permisos.md'
    - 'Contribucions': 'civicrm/contribucions.md'
    - 'Processos habituals':
        - 'Combinaci贸 de contactes': 'civicrm/processos-habituals/combinacio-contactes.md'
    - 'Preguntes m茅s freq眉ents': 'civicrm/preguntes-mes-frequents.md'
    - "Annex: Llistat d'idiomes": 'civicrm/annex-idiomes.md'
- Infncia:
    - 'Introducci贸': 'infancia/index.md'
    - 'Contactes': 'infancia/contactes.md'
    - 'Activitats': 'infancia/activitats.md'
    - 'Relacions': 'infancia/relacions.md'
    - 'Esdeveniments': 'infancia/esdeveniments.md'
    - 'Grups': 'infancia/grups.md'
    - 'Contribucions': 'infancia/contribucions.md'
    - 'Perfils': 'infancia/perfils.md'
    - 'Permisos': 'infancia/permisos.md'
    - "Guia d'煤s": 'infancia/guia-us.md'
    - 'Preguntes m茅s freq眉ents': 'infancia/preguntes-mes-frequents.md'
- Adults:
    - 'Introducci贸': 'adults/index.md'
    - 'Contactes': 'adults/contactes.md'
    - 'Activitats': 'adults/activitats.md'
    - 'Parella ling眉铆stica':
       - 'Relacions': 'adults/parella-linguistica/relacions.md'
- Atenci贸 social:
    - 'Activitats': 'atencio-social/activitats.md'
- Voluntariat, prctiques i educaci贸 en el lleure:
    - 'Introducci贸': 'voluntariat-practiques-educacio-lleure/index.md'
    - 'Voluntariat':
       - 'Introducci贸': 'voluntariat-practiques-educacio-lleure/voluntariat/index.md'
       - 'Contactes': 'voluntariat-practiques-educacio-lleure/voluntariat/contactes.md'
       - 'Activitats': 'voluntariat-practiques-educacio-lleure/voluntariat/activitats.md'
       - 'Relacions': 'voluntariat-practiques-educacio-lleure/voluntariat/relacions.md'
       - 'Grups': 'voluntariat-practiques-educacio-lleure/voluntariat/grups.md'
       - 'Formularis': 'voluntariat-practiques-educacio-lleure/voluntariat/formularis.md'
       - 'Informes': 'voluntariat-practiques-educacio-lleure/voluntariat/informes.md'
       - 'Esdeveniments': 'voluntariat-practiques-educacio-lleure/voluntariat/esdeveniments.md'
       - 'Plantilles de missatges': 'voluntariat-practiques-educacio-lleure/voluntariat/plantilles-de-missatges.md'
       - 'Permisos': 'voluntariat-practiques-educacio-lleure/voluntariat/permisos.md'
       - "Guia d'煤s": 'voluntariat-practiques-educacio-lleure/voluntariat/guia-us.md'
    - 'Prctiques': 'voluntariat-practiques-educacio-lleure/practiques/index.md'
    - 'Educaci贸 en el lleure': 'voluntariat-practiques-educacio-lleure/educacio-en-el-lleure/index.md'
- Esdeveniments:
    - 'Introducci贸': 'esdeveniments/index.md'
    - 'Preguntes m茅s freq眉ents': 'esdeveniments/preguntes-mes-frequents.md'
- Comunicaci贸:
    - 'Introducci贸': 'comunicacio/index.md'
    - 'Preguntes m茅s freq眉ents': 'comunicacio/preguntes-mes-frequents.md'
- Captaci贸 de fons:
    - "Guia d'煤s": 'captacio-de-fons/guia-us.md'
    - "Conceptes clau": 'captacio-de-fons/conceptes-clau.md'
    - "Declaraci贸 i certificaci贸 de donatius (182 i 993)" : 'captacio-de-fons/declaracio-certificacio-donatius'
    - "StockCrowd (EN DESENVOLUPAMENT)": 'captacio-de-fons/stockcrowd.md'
- Banc d'Aliments:
    - "Guia d'煤s": 'banc-aliments/guia-us.md'
    - 'Definici贸': 'banc-aliments/definicio.md'
- Gent gran:
    - 'Introducci贸': 'gent-gran/index.md'
- CIE:
    - 'Introducci贸': 'cie/index.md'
    - 'Contactes': 'cie/contactes.md'
    - 'Activitats': 'cie/activitats.md'
    - 'Relacions': 'cie/relacions.md'
    - 'Grups': 'cie/grups.md'
    - 'Permisos': 'cie/permisos.md'
    - 'Perfils': 'cie/perfils.md'
- Xarxa d'Hospitalitat:
    - 'Definici贸': 'xarxa-hospitalitat/definicio.md'
    - "Guia d'煤s": 'xarxa-hospitalitat/guia-us.md'
- Imprescindibles : 'imprescindibles.md'

theme:
  name: material
  language: ca
  palette:
    primary: red
    accent: red
  icon:
    logo: material/book
  favicon: favicon.png

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - glightbox

extra:
  analytics:
    provider: google
    property: 'G-CHW6R3GJZR'
